language: node_js
node_js:
- '6'
- '7'
- '8'
notifications:
  slack:
    secure: RBIJ21eOQnOxew32aY9slKbiiRbuXrkTWC2FLE+QyIDS3BesJdDTnjsI/WWHTJE3JquizRaOVU0AqN5i2D1JAgtkBXPBYcA1C8HoW/ehEXTWhPgee8QMXVf2MYLMh6ms9UM5OZi+w0V03mxg2K/sKinvVuezmCaDm9k38D8xF0+QQLUUx5pia22/EZmMRH3Bu8IfQ6zIbusVEqqozS3NYuPEw0RETbZnxFDI3QlN2t4SkZ9JMoS6+zR1fErz6c05GVLwcoOz21BvZgGud6SPm2/VZf0d06AMPAA4MKsuGjUrz676MMqG8x1LAZbHu6q/pJxshZkgjo3zTYqnxLPLg1GmxLUSyboskYGKDd2DS9F+DdVoqIKEQhifey2vl+qkO9ax9fJVhm2OCdxMGCVYHk0erWBzjN9zT52EXJI8U6JgHRzYLEgtFbsKSDOXYID/q6JdJ+d+BZlOIT2xiiJh20xnFPgWbKuJMi0HJzYdHCgjAO6gBLawdzyvVC1FT2DEYYIRdWTThgHm3iOur9gD9BC0cElUV+o53mtF/DzJcH2I3gNTCA7ViJMIYdBQomctMpoX2Q+FyTfiY0CPcmxB/56pnyyLXSQXZ2Fe2prpLome79Es2371DHx0C3P9OKcp1d7119xQ2FHtiRgzaS98mnKyapItKziDvny7M1S5GRc=
